version: '3'
services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    ports:
      - ${DRONE_SERVER_PORT:-8000}:80
    volumes:
      - ./drone:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_DEBUG=true
      - DRONE_LOGS_TRACE=true
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=http
      - DRONE_GOGS=true
      - DRONE_GOGS_SERVER=${DRONE_GOGS_SERVER}
      - TZ=Asia/Shanghai

  drone-runner-docker:
    image: drone/drone-runner-docker:latest
    container_name: drone-runner-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=​drone-server
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=DockerRunner
      - TZ=Asia/Shanghai

networks:
  devops:
    external: true
